# Generated by Django 4.2.6 on 2023-11-01 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendence', '0002_remove_studentdata_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='vESP',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='vRFID',
            field=models.BooleanField(default=False),
        ),
    ]
